version = 0.1

[default.deploy.parameters]
stack_name = "ruztiq-fraud-detection"
resolve_s3 = true
s3_prefix = "ruztiq-fraud-detection"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBSecretArn=\"DBSecretArn\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
