AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: SentinelIQ Fraud Detection Platform

Globals:
  Function:
    Runtime: python3.11
    Timeout: 900
    MemorySize: 512

Resources:

  TransactionsTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: Transactions

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: transaction_reference
          AttributeType: S

      KeySchema:
        - AttributeName: transaction_reference
          KeyType: HASH

  FraudResultsTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: FraudResults

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: transaction_reference
          AttributeType: S

      KeySchema:
        - AttributeName: transaction_reference
          KeyType: HASH

  FraudDetectionFunction:
    Type: AWS::Serverless::Function

    Properties:

      CodeUri: ..

      Handler: src/lambda_function/handler.lambda_handler

      Runtime: python3.11

      Architectures:
        - x86_64

      Events:

        ScoreAPI:

          Type: Api

          Properties:

            Path: /score

            Method: post

      Policies:

        - AWSLambdaBasicExecutionRole

        - DynamoDBCrudPolicy:
            TableName: !Ref TransactionsTable

        - DynamoDBCrudPolicy:
            TableName: !Ref FraudResultsTable

        #
        # CloudWatch Custom Metrics
        #
        - Statement:
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: "*"

      Environment:

        Variables:

          BATCH_SIZE: "100"

          TRANSACTIONS_TABLE: !Ref TransactionsTable

          FRAUD_RESULTS_TABLE: !Ref FraudResultsTable

Outputs:

  FraudDetectionFunction:
    Description: Lambda ARN
    Value: !GetAtt FraudDetectionFunction.Arn

  ApiEndpoint:
    Description: API Gateway Endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/score"

  TransactionsTableName:
    Description: Transactions Table
    Value: !Ref TransactionsTable

  FraudResultsTableName:
    Description: Fraud Results Table
    Value: !Ref FraudResultsTable